### ISSUE TITLE
Cannot install/compile

### ISSUE THREAD

**Issue by t-lou** [Hedgehog-Computing/hedgehog-lab#181]
**Describe the bug**
Cannot compile following the readme.

**To Reproduce**
- git clone https://github.com/Hedgehog-Computing/hedgehog-lab.git
- cd hedgehog-lab
- git checkout master
- yarn install

**Expected behavior**
Some installation or compilation happens.

**Screenshots**
![Screenshot_2022-05-06_19-27-40](https://user-images.githubusercontent.com/16481337/167184434-891a07ef-b403-45bc-8ca7-3f8642bc5c16.png)

**Desktop (please complete the following information):**
 - OS: debian 11

If yarn is another program outside _cmdtest_, please add the instruction of installation. Not everyone is JS developer.

**Comment by AGDholo** [comment]
Hi @t-lou , please use the dev branch, master branch is currently abandoned.

**Comment by t-lou** [comment]
The same output

**Comment by AGDholo** [comment]
It seems like the `yarn` command issues, pls make sure you are already enabled the `yarn`.

**Comment by t-lou** [comment]
would be great if a link for yarn were included in readme

**Comment by AGDholo** [comment]
> would be great if a link for yarn were included in readme

Yeah, I will do it, thank you for your suggestion.
