### ISSUE TITLE
Minor issue, typo in Hedgehog Book

### ISSUE THREAD

**Issue by zc2214** [Hedgehog-Computing/hedgehog-lab#192]
It seems that the Hedgehog Book is still under construction; the content on the Function and Class page is empty. But one thing that needs to fix is that "Function" is mistyped as "Functiobn." Looking forward to learning from Hedgehog Book!

**Comment by AGDholo** [comment]
Hi @zc2214 

Thanks for your suggestion.
New book is under development: https://github.com/Hedgehog-Computing/docs/tree/convert-to-docusaurus
