### ISSUE TITLE
要不要开个Slack或者Facebook群组一起聊天？

### ISSUE THREAD

**Issue by lidangzzz** [Hedgehog-Computing/hedgehog-lab#23]
如题

**Comment by AGDholo** [comment]
附议

**Comment by jmnie** [comment]
slack or discord(recommeded).

**Comment by lidangzzz** [comment]
@AGDholo @jmnie 开好了：projecthedgehoglab.slack.com

**Comment by AGDholo** [comment]
> slack or discord(recommeded).
> discord管理感觉很方便，最近见过的一个开源项目就是用discord的。

我在 vuetify 工作的时候用的是 discord
material-ui 工作的时候用的是 slack

这两个开源项目用的比较多

**Comment by AGDholo** [comment]
@lidangzzz slack 需要邀请才能进入吧

**Comment by jmnie** [comment]
> @lidangzzz slack 需要邀请才能进入吧
+1，应该是需要邀请

**Comment by lidangzzz** [comment]
@AGDholo @jmnie 啊啊啊错了，是这个：
https://join.slack.com/t/projecthedgehoglab/shared_invite/zt-fuqb1s1i-2G2hynL6Up7dZghz3rN2VA

比心

**Comment by jansona** [comment]
真的是师老党立吗？可以哦

**Comment by ChihweiLHBird** [comment]
> @AGDholo @jmnie 啊啊啊错了，是这个：
> https://join.slack.com/t/projecthedgehoglab/shared_invite/zt-fuqb1s1i-2G2hynL6Up7dZghz3rN2VA
> 
> 比心

This link is no longer active?

**Comment by AGDholo** [comment]
> This link is no longer active?

@ChihweiLHBird 
https://join.slack.com/t/projecthedgehoglab/shared_invite/zt-kzzbxp5s-WXY8w4xQtgJ5dOditNRGFQ

**Comment by tangkg** [comment]
> > This link is no longer active?
> 
> @ChihweiLHBird
> https://join.slack.com/t/projecthedgehoglab/shared_invite/zt-kzzbxp5s-WXY8w4xQtgJ5dOditNRGFQ

The link is no longer active either.

**Comment by Himself65** [comment]
resolved, closing
