### ISSUE TITLE
[Feature request] function overload

### ISSUE THREAD

**Issue by cjbd** [Hedgehog-Computing/hedgehog-lab#79]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
class function overload like Java/C++

**Describe alternatives you've considered**
no good alternative i can think of right now

**Additional context**
Hello, this is really awesome project, i saw you modified 'foxbenjaminfox/babel-plugin-overload' for operator overload, this is really great feature, is it possible for class function overload? thanks!

**Comment by lidangzzz** [comment]
It depends on features of JavaScript and Babel preset. Based on what I know, you can do that.

**Comment by cjbd** [comment]
@lidangzzz , thanks for the update!
do you have any example of using babel&typescript to achieve function overload?
