### ISSUE TITLE
UI suggestion on Upload and Save buttons

### ISSUE THREAD

**Issue by ydzhou** [Hedgehog-Computing/hedgehog-lab#82]
**Is your feature request related to a problem? Please describe.**
Current "upload" and "save" buttons are confusing to me. Those buttons are to upload a new file to the YouCode session or save YouCode session into a local file. But they are placed inside the sidebar, which feel unrelated to YouCode session.

**Describe the solution you'd like**
Re-position two buttons from sidebar to YouCode session. Replace them with icons to avoid information overload. By doing so, customers have a clear understanding on both upload and save actions are related to YouCode session. Actually upload can be considered as "Open a new file", so open can be the alternative name for that button.

I am happy to do the code change once we anchor down the details.

**Additional context**
The left icon is for uploading a file into YouCode session and the right icon is to save current YouCode session into a local file.
<img width="736" alt="截屏2020-11-07 下午4 22 02" src="https://user-images.githubusercontent.com/3310714/98454141-0ada2e00-2116-11eb-9940-00c4e385cea2.png">

**Comment by lidangzzz** [comment]
Thanks for your advice
