### ISSUE TITLE
Unable to build hedgehog-lab in Darwin ARM system

### ISSUE THREAD

**Issue by zhong-yiyu** [Hedgehog-Computing/hedgehog-lab#89]
**Describe the bug**
Under the macOS system based on ARM64 system, when executes `yarn install` command, it throws errors about gyp toolchains.

**To Reproduce**
1. Enter the codebase
2. Run `yarn install`

The error looks like this:
```
Output:
prebuild-install WARN install No prebuilt binaries found (target=16.2.0 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.2.0 | darwin | arm64
```

**Desktop (please complete the following information):**
 - OS: [Apple Darwin]

**Additional context**
It's not a big problem, probably due to `gpu.js` module.

**Comment by Himself65** [comment]
it's a upstream issue: https://github.com/gpujs/gpu.js/issues/711

**Comment by Himself65** [comment]
No, dont close this until the bug fixes

**Comment by Himself65** [comment]
I'm currently fixing this issue
