### ISSUE TITLE
为“高能”客户提供更多加减乘除的计算功能

### ISSUE THREAD

**Issue by qishen** [Hedgehog-Computing/hedgehog-lab#94]
立党老师创建这个网页计算器难道是因为赞同陈平老师说的“MATLAB 为低能的客户提供方便的程序集成”？哈哈哈 @lidangzzz 

建议加入更多科学计算工具集比如二进制加减法超越MATLAB实现陈平老师的梦想！

**Comment by Himself65** [comment]
closed and locked as an invalid issue
